In [1]:
import csv
import pandas as pd
import os
import re

In [3]:
variables = ["j_C", "f_D", "file", "input_instance", "Re_C", "Re_H", "cmp_fiber", "cmp_TC", "rmsd_fiber", "rmsd_TC", "cmp_hyd",
            "cmp_tmp", "cmp_hxt", "rmsd_DP", "rmsd_Tout", "rmsd_qdot"]

key_variables = ['j_C', 'f_D', 'Re_C', 'Re_H', "rmsd_fiber", "rmsd_TC", "rmsd_DP", "rmsd_Tout"]

def clean_data(data):
    final = []
    cut2 = None
    for var in variables:
        if cut2 == None:
            cut2 = data
        cut1 = cut2.split(var)[0]
        cut2 = var + cut2.split(var)[1]
        final.append(cut1)

    final = [x.replace('=', ',') for x in final[1:]]
    final_data = []
    for var in final:
        important = False
        for variable in key_variables:
            if var.startswith(variable):
                important = True
        if important:
            final_data.append(var)

    final_data = [x.split(",")[1].strip() for x in final_data]    
    return final_data

In [9]:
def build_dataframe_list():
    final = []
    files = os.listdir('ZZoutput')
    for file in files:
        pathname = "ZZoutput\\" + file
        with open(pathname) as f:
            data = f.read().replace('\n', '') 
            data = re.findall(r"j_C.+", data)[0]
            row = clean_data(data)
        final.append(row)
    return final    
            
            
data = build_dataframe_list()

In [10]:
df = pd.DataFrame(data, columns=key_variables)
df.to_csv('ZZoutput.csv', index=False)
df

,j_C,f_D,Re_C,Re_H,rmsd_fiber,rmsd_TC,rmsd_DP,rmsd_Tout
0,0.0050,0.4507,2.4956e+03,3.0004e+03,33.0406,33.0703,1.5079e+03,23.3583
1,0.0052,0.4507,2.4920e+03,2.9981e+03,32.6254,31.4406,1.5153e+03,21.2573
2,0.0055,0.4507,2.4886e+03,2.9958e+03,32.2536,29.9166,1.5226e+03,19.3206
3,0.0057,0.4507,2.4852e+03,2.9930e+03,31.8924,28.3727,1.5304e+03,17.3882
4,0.0060,0.4507,2.4818e+03,2.9901e+03,31.5573,26.8763,1.5382e+03,15.5448
...,...,...,...,...,...,...,...,...
96,0.4159,0.4507,2.3431e+03,2.7475e+03,24.5512,19.4003,1.8057e+03,33.9007
97,0.4355,0.4507,2.3427e+03,2.7468e+03,24.5136,19.4341,1.8051e+03,33.9452
98,0.4560,0.4507,2.3424e+03,2.7462e+03,24.4764,19.4662,1.8046e+03,33.9878
99,0.4775,0.4507,2.3420e+03,2.7456e+03,24.4439,19.4968,1.8041e+03,34.0284
100,0.5000,0.4507,2.3416e+03,2.7451e+03,24.4101,19.5261,1.8037e+03,34.0673